baseurl = "https://spidey.host"
defaultContentLanguage = "en"
languageCode = "en"
title = "Spidey Blogs"

[services]
[services.disqus]
shortname = ""
# [services.googleAnalytics]
# ID = ""

[params]
lightTheme = "emerald"
darkTheme = "forest"

# backgroundImage = "me/background.jpg"
# backgroundImageDark = ""

author = "Spidey"
# description = ""
avatar = "img/avatar.png"
headerTitle = "Spidey Blogs"
# motto = ""

# footerBottomText = ""

# rss = true

# utterancesRepo = ""

# valine = true
# LEANCLOUD_APP_ID = ""
# LEANCLOUD_APP_KEY = ""
# VALINE_LANGUAGE = ""

email = "contact@spidey.host"

#siteStartYear = 2016

# favicon = "favicon.ico"

# Syntax highlighting
# customSyntaxHighlighting = true

# options
# stickyNav = true
# reorderNavItems = ["search", "rss", "posts", "categories", "tags"]
# collapseNavItems = ["posts", "categories", "tags"]
# showTableOfContents = true
# showSummaryCoverInPost = true
# showPrevNextPost = true
# hasTwitterEmbed = true

# [params.navItems]

# [params.advanced]
# customCSS = ["css/custom.css"]
# customJS = []

# [params.experimental]
# jsDate = true
# jsDateFormat = "yyyy年MM月dd日"
