name = "Dream"
license = "MIT"
description = ""

homepage = "https://g1en.site/hugo-theme-dream"

demoSite = "https://g1en.site"

tags = ["blog", "responsive", "light", "dark", "personal", "creative"]
features = [
  "Creative",
  "Masonry Layout",
  "Flippable About Page",
  "Google Analytics",
  "Disqus",
  "Utterances",
  "I18n",
  "Search",
  "Syntax Highlighting",
  "Decap CMS",
  "Customizable",
]

[author]
name = "Yue Yang"
homepage = "https://github.com/g1eny0ung"
